# Generated by Django 4.1.2 on 2022-11-30 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=None, max_length=100)),
                ('lastName', models.CharField(default=None, max_length=100)),
                ('profession', models.CharField(default=None, max_length=100)),
                ('income', models.BigIntegerField(default=0, max_length=5000000000000000)),
                ('familyLead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default=None, max_length=100)),
                ('expense', models.BigIntegerField(default=0, max_length=100000000000000000)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('familyLead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FamilyExpenseTrackerApp.familymembers')),
            ],
        ),
    ]
